<?php

return [
    'categories' => [
        'joints' => ['SML', 'GME', 'MSJ', 'QNC'],
        'digestion' => ['MNJ', 'PRP', 'KMQ'],
        'recovery' => ['ALB', 'GME', 'MNJ', 'QNC'],
        'respiratory' => ['PRP'],
        'immunity' => ['PRP', 'KLR', 'SQU', 'SMC'],
        'nutrition' => ['KMQ', 'ETK', 'KLR', 'ALB', 'HEX'],
        'cardiovascular' => ['GAR', 'SQU'],
        'metabolic' => ['GAR'],
        'male_vitality' => ['RAD'],
        'skin' => ['PSK', 'NOUD'],
        'womens_health' => ['SWN'],
        'oral' => ['PRP'],
        'sleep_stress' => ['SAF'],
        'cognitive' => ['PEG'],
        'eye_health' => ['LMT'],
        'hemorrhoid' => ['AMB'],
        'prostate' => ['LYC'],
        'unsupported_health' => ['KLR'],
    ],
    'labels' => [
        'joints' => 'kenyamanan sendi dan pemulihan jaringan',
        'digestion' => 'kenyamanan lambung dan pencernaan',
        'recovery' => 'pemulihan tubuh dan kebutuhan protein',
        'respiratory' => 'batuk ringan dan kenyamanan tenggorokan',
        'immunity' => 'daya tahan tubuh dan kebutuhan antioksidan',
        'nutrition' => 'pemenuhan nutrisi dan kebugaran',
        'cardiovascular' => 'pola hidup sehat untuk tekanan darah dan kolesterol',
        'metabolic' => 'pendamping pola hidup untuk metabolisme dan gula darah',
        'male_vitality' => 'stamina dan vitalitas pria',
        'skin' => 'pemulihan dan kenyamanan kulit',
        'womens_health' => 'kebersihan dan kesehatan wanita',
        'oral' => 'kenyamanan mulut dan tenggorokan',
        'sleep_stress' => 'relaksasi dan rutinitas tidur sehat',
        'cognitive' => 'konsentrasi dan kebugaran kognitif',
        'eye_health' => 'nutrisi dan pemeliharaan kesehatan mata',
        'hemorrhoid' => 'kelancaran BAB dan kenyamanan pada wasir ringan',
        'prostate' => 'antioksidan dan pemeliharaan kesehatan prostat',
        'unsupported_health' => 'pemenuhan nutrisi agar tubuh tetap sehat dan fit',
    ],
    'soft_selling_mechanisms' => [
        'SML' => 'Perpaduan akar kuning, bratawali, dan daun salam digunakan secara tradisional untuk membantu mendukung kenyamanan sendi dan otot.',
        'MNJ' => 'Protein, kolagen, GAGs, dan asam amino dari teripang membantu mendukung pemeliharaan jaringan serta proses pemulihan tubuh.',
        'RAD' => 'Pasak bumi dan jahe merah digunakan secara tradisional untuk membantu mendukung stamina, sedangkan susu kambing dan kedelai melengkapi energi serta protein.',
    ],
];
